services:
  app:
    build: ./services/app
    container_name: app-services
    ports:
      - "4002:4002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
  user:
    build: ./services/users
    container_name: user-services
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=${MONGODB_URL}
  orchestrator:
    build: ./orcestrator-grapsql
    container_name: orcestrator-grapsql
    ports:
      - "80:4000"
    environment:
      - APP_SERVER_URL=${APP_SERVER_URL}
      - USER_SERVER_URL=${USER_SERVER_URL}
      - REDIS_URL=${REDIS_URL}